deployment:
  replicas: 3

service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Cluster

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  web:
    port: 8000
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443

log:
  level: INFO

accessLog:
  enabled: true
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop

api:
  dashboard: true
  insecure: false
