apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: kernelcafe
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.12.1
    helm:
      values: |
        defaultSettings:
          defaultDataPath: /var/mnt/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
