apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: kernelcafe
  source:
    repoURL: https://github.com/systemdbrew/kernelcafe.git
    targetRevision: main
    path: infrastructure/vault
    directory:
      include: monitoring.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 10
