apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-network
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "24"
spec:
  project: kernelcafe
  source:
    repoURL: https://github.com/systemdbrew/kernelcafe.git
    targetRevision: main
    path: infrastructure/networking/storage-network
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
