apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "36"
spec:
  project: kernelcafe
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 18.13.1
      helm:
        valueFiles:
          - $values/infrastructure/loki/values.yaml
    - repoURL: https://github.com/systemdbrew/kernelcafe.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
