apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "36"
spec:
  project: kernelcafe
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.45.2
    helm:
      values: |
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
